version: '3.9'
services:
  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017  
    volumes:
      - /c/Users/aleja/Documentos/curso_alura/db-mongo-ecomm

  ecomm:
    image: eduardov/ecomm:1.0




    
  
    

    
    