db.accounts.insertMany([
    {
      nome_user: "ejeremias",
      email: "jeremias@example.com",
      senha: "02055",
      dataCriacao: new Date(),
      cpf: "71586924511",
      telefone: "1234567890",
      endereco: {
        bairro: "jaburandi",
        rua: "Rua Principal",
        numero: "6894",
        complemento: "apto 5",
        cep: "12345678",
        cidade: "Parana",
        uf: "PR",
      },
    },
    {
      nome_user: "esmirna",
      email: "esmirna@example.com",
      senha: "65986",
      dataCriacao: new Date(),
      cpf: "98463215722",
      telefone: "1234567890",
      endereco: {
        bairro: "taruma",
        rua: "Rua nova",
        numero: "6589",
        complemento: "apto 14",
        cep: "75814502",
        cidade: "Rio de Janeiro",
        uf: "RJ",
      },
    },
    {
      nome_user: "selene",
      email: "selene@example.com",
      senha: "65894",
      dataCriacao: new Date(),
      cpf: "69845231255",
      telefone: "66978423557",
      endereco: {
        bairro: "caroni",
        rua: "5",
        numero: "4587",
        complemento: "apto 2",
        cep: "87508142",
        cidade: "maringa",
        uf: "PR",
      },
    },
  ]);